**Experiment - 2 : Apply data cleaning techniques (e.g. Data Imputation)**

In [ ]:
#import libraries
import pandas as pd
import numpy as np

In [ ]:
#load the data
data=pd.read_csv("/content/Tamilnadu agriculture yield data - Tamilnadu agriculture yield data.csv")
data.head()   #initial dataset

   State_Name District_Name  Crop_Year Season       Crop     Area  Production
0  Tamil Nadu      ARIYALUR     2008.0    NaN       Rice  24574.0         NaN
1  Tamil Nadu      ARIYALUR     2008.0    NaN  Arhar/Tur    209.0         NaN
2  Tamil Nadu      ARIYALUR     2008.0    NaN      Bajra    565.0         NaN
3  Tamil Nadu      ARIYALUR     2008.0    NaN     Banana    190.0         NaN
4  Tamil Nadu      ARIYALUR     2008.0    NaN  Cashewnut  31113.0         NaN

In [ ]:
#check for null values
print(data.isnull().sum())

State_Name        27
District_Name     13
Crop_Year          9
Season            20
Crop               7
Area              10
Production       281
dtype: int64

In [ ]:
#data dimensions
print(data.shape)

(13547, 7)

**Most Frequent Value**

In [ ]:
from sklearn.impute import SimpleImputer
frequent_val=SimpleImputer(missing_values=np.nan,strategy='most_frequent')

In [ ]:
#replacing all of the missing data with the most frequent value
data["State_Name"]=frequent_val.fit_transform(data[["State_Name"]])
data["District_Name"]=frequent_val.fit_transform(data[["District_Name"]])
data["Crop_Year"]=frequent_val.fit_transform(data[["Crop_Year"]])
data["Season"]=frequent_val.fit_transform(data[["Season"]])
data["Crop"]=frequent_val.fit_transform(data[["Crop"]])
data["Area"]=frequent_val.fit_transform(data[["Area"]])
data["Production"]=frequent_val.fit_transform(data[["Production"]])

In [ ]:
#printing the preprocessed dataset
data

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Tamil Nadu,ARIYALUR,2008.0,Whole Year,Rice,24574.0,0.0
1,Tamil Nadu,ARIYALUR,2008.0,Whole Year,Arhar/Tur,209.0,0.0
2,Tamil Nadu,ARIYALUR,2008.0,Whole Year,Bajra,565.0,0.0
3,Tamil Nadu,ARIYALUR,2008.0,Whole Year,Banana,190.0,0.0
4,Tamil Nadu,ARIYALUR,2008.0,Whole Year,Cashewnut,31113.0,0.0
...,...,...,...,...,...,...,...
13542,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Small millets,1187.0,676.0
13543,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Sugarcane,2917.0,296017.0
13544,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Sweet potato,4.0,84.0
13545,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Tapioca,4.0,120.0
13546,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Turmeric,4.0,15.0

In [ ]:
print(data.isna().sum())

State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

**Using KNN Imputer**

In [ ]:
#load the data
data=pd.read_csv("/content/Tamilnadu agriculture yield data - Tamilnadu agriculture yield data.csv")
data.head()   #initial dataset

   State_Name District_Name  Crop_Year Season       Crop     Area  Production
0  Tamil Nadu      ARIYALUR     2008.0    NaN       Rice  24574.0         NaN
1  Tamil Nadu      ARIYALUR     2008.0    NaN  Arhar/Tur    209.0         NaN
2  Tamil Nadu      ARIYALUR     2008.0    NaN      Bajra    565.0         NaN
3  Tamil Nadu      ARIYALUR     2008.0    NaN     Banana    190.0         NaN
4  Tamil Nadu      ARIYALUR     2008.0    NaN  Cashewnut  31113.0         NaN

In [ ]:
print(data.isna().sum())

State_Name        27
District_Name     13
Crop_Year          9
Season            20
Crop               7
Area              10
Production       281
dtype: int64

In [ ]:
#handle categorical data
new_data=pd.get_dummies(data,drop_first=True)
new_data #121 columns after handling categorical values

,Crop_Year,Area,Production,District_Name_COIMBATORE,District_Name_CUDDALORE,District_Name_DHARMAPURI,District_Name_DINDIGUL,District_Name_ERODE,District_Name_KANCHIPURAM,District_Name_KANNIYAKUMARI,...,Crop_Tobacco,Crop_Tomato,Crop_Total foodgrain,Crop_Turmeric,Crop_Turnip,Crop_Urad,Crop_Varagu,Crop_Water Melon,Crop_Wheat,Crop_Yam
0,2008.0,24574.0,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2008.0,209.0,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2008.0,565.0,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2008.0,190.0,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2008.0,31113.0,NaN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13542,2013.0,1187.0,676.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13543,2013.0,2917.0,296017.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13544,2013.0,4.0,84.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13545,2013.0,4.0,120.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13546,2013.0,4.0,15.0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [ ]:
#use KNN Imputer
from sklearn.impute import KNNImputer
knn=KNNImputer(n_neighbors=2)
imputed_data=knn.fit_transform(new_data)
final_data=pd.DataFrame(imputed_data)

In [ ]:
#check for null values in the imputed dataset
final_data.isna().sum()

0      0
1      0
2      0
3      0
4      0
      ..
116    0
117    0
118    0
119    0
120    0
Length: 121, dtype: int64

**Mean or Median value**

In [ ]:
data=pd.read_csv("/content/Tamilnadu agriculture yield data - Tamilnadu agriculture yield data.csv")
data.head()

   State_Name District_Name  Crop_Year Season       Crop     Area  Production
0  Tamil Nadu      ARIYALUR     2008.0    NaN       Rice  24574.0         NaN
1  Tamil Nadu      ARIYALUR     2008.0    NaN  Arhar/Tur    209.0         NaN
2  Tamil Nadu      ARIYALUR     2008.0    NaN      Bajra    565.0         NaN
3  Tamil Nadu      ARIYALUR     2008.0    NaN     Banana    190.0         NaN
4  Tamil Nadu      ARIYALUR     2008.0    NaN  Cashewnut  31113.0         NaN

In [ ]:
#initialize simple imputer for median
med=SimpleImputer(missing_values=np.nan,strategy='median')

#apply frequent values on categorical columns
data["State_Name"]=frequent_val.fit_transform(data[["State_Name"]])
data["District_Name"]=frequent_val.fit_transform(data[["District_Name"]])
data["Crop_Year"]=frequent_val.fit_transform(data[["Crop_Year"]])
data["Season"]=frequent_val.fit_transform(data[["Season"]])
data["Crop"]=frequent_val.fit_transform(data[["Crop"]])

#apply median values on numerical columns
data["Area"]=med.fit_transform(data[["Area"]])
data["Production"]=med.fit_transform(data[["Production"]])

In [ ]:
#imputed data now
data

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Tamil Nadu,ARIYALUR,2008.0,Whole Year,Rice,24574.0,841.0
1,Tamil Nadu,ARIYALUR,2008.0,Whole Year,Arhar/Tur,209.0,841.0
2,Tamil Nadu,ARIYALUR,2008.0,Whole Year,Bajra,565.0,841.0
3,Tamil Nadu,ARIYALUR,2008.0,Whole Year,Banana,190.0,841.0
4,Tamil Nadu,ARIYALUR,2008.0,Whole Year,Cashewnut,31113.0,841.0
...,...,...,...,...,...,...,...
13542,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Small millets,1187.0,676.0
13543,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Sugarcane,2917.0,296017.0
13544,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Sweet potato,4.0,84.0
13545,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Tapioca,4.0,120.0
13546,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Turmeric,4.0,15.0

In [ ]:
print(data.isnull().sum())

State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

**Fixed Value**

In [ ]:
data=pd.read_csv("/content/Tamilnadu agriculture yield data - Tamilnadu agriculture yield data.csv")
data.head()

   State_Name District_Name  Crop_Year Season       Crop     Area  Production
0  Tamil Nadu      ARIYALUR     2008.0    NaN       Rice  24574.0         NaN
1  Tamil Nadu      ARIYALUR     2008.0    NaN  Arhar/Tur    209.0         NaN
2  Tamil Nadu      ARIYALUR     2008.0    NaN      Bajra    565.0         NaN
3  Tamil Nadu      ARIYALUR     2008.0    NaN     Banana    190.0         NaN
4  Tamil Nadu      ARIYALUR     2008.0    NaN  Cashewnut  31113.0         NaN

In [ ]:
print(data.isna().sum())

State_Name        27
District_Name     13
Crop_Year          9
Season            20
Crop               7
Area              10
Production       281
dtype: int64

In [ ]:
#apply fill values to columns using pandas
data["State_Name"].fillna("Tamil Nadu",inplace=True)
data["District_Name"].fillna("COIMBATORE",inplace=True)
data["Crop_Year"].fillna("2000",inplace=True)
data["Season"].fillna("Kharif",inplace=True)
data["Crop"].fillna("Maize",inplace=True)
data["Area"].fillna("5500",inplace=True)
data["Production"].fillna("12000",inplace=True)

#print the imputed dataset
data.head()

   State_Name District_Name Crop_Year  Season       Crop     Area Production
0  Tamil Nadu      ARIYALUR    2008.0  Kharif       Rice  24574.0      12000
1  Tamil Nadu      ARIYALUR    2008.0  Kharif  Arhar/Tur    209.0      12000
2  Tamil Nadu      ARIYALUR    2008.0  Kharif      Bajra    565.0      12000
3  Tamil Nadu      ARIYALUR    2008.0  Kharif     Banana    190.0      12000
4  Tamil Nadu      ARIYALUR    2008.0  Kharif  Cashewnut  31113.0      12000

In [ ]:
print(data.isna().sum())

State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

**Replace missing values with min/max value**

In [ ]:
data=pd.read_csv("/content/Tamilnadu agriculture yield data - Tamilnadu agriculture yield data.csv")
data.tail()

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
13542,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Small millets,1187.0,676.0
13543,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Sugarcane,2917.0,296017.0
13544,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Sweet potato,4.0,84.0
13545,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Tapioca,4.0,120.0
13546,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Turmeric,4.0,15.0

In [ ]:
print(data.isna().sum())

State_Name        27
District_Name     13
Crop_Year          9
Season            20
Crop               7
Area              10
Production       281
dtype: int64

In [ ]:
#apply max/min values
data["State_Name"].fillna("Tamil Nadu",inplace=True)
data["District_Name"].fillna("CHENNAI",inplace=True)
data["Crop_Year"].fillna("2000",inplace=True)
data["Season"].fillna("Kharif",inplace=True)
data["Crop"].fillna("Maize",inplace=True)

#fill with max values
max_area=data["Area"].max()
data["Area"].fillna(min_area,inplace=True)

max_prod=data["Production"].max()
data["Production"].fillna(max_prod,inplace=True)
print(data.isna().sum())

State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

In [ ]:
#imputed data
data

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Tamil Nadu,ARIYALUR,2008.0,Kharif,Rice,24574.0,1.250800e+09
1,Tamil Nadu,ARIYALUR,2008.0,Kharif,Arhar/Tur,209.0,1.250800e+09
2,Tamil Nadu,ARIYALUR,2008.0,Kharif,Bajra,565.0,1.250800e+09
3,Tamil Nadu,ARIYALUR,2008.0,Kharif,Banana,190.0,1.250800e+09
4,Tamil Nadu,ARIYALUR,2008.0,Kharif,Cashewnut,31113.0,1.250800e+09
...,...,...,...,...,...,...,...
13542,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Small millets,1187.0,6.760000e+02
13543,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Sugarcane,2917.0,2.960170e+05
13544,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Sweet potato,4.0,8.400000e+01
13545,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Tapioca,4.0,1.200000e+02
13546,Tamil Nadu,VIRUDHUNAGAR,2013.0,Whole Year,Turmeric,4.0,1.500000e+01